# Elasticsearch Configuration
cluster.name: eco-dex-cluster
node.name: ${HOSTNAME}

# Network
network.host: 0.0.0.0
http.port: 9200

# Discovery
discovery.type: single-node

# Paths
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Memory
bootstrap.memory_lock: true

# Security
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true

# Performance
indices.memory.index_buffer_size: 30%
thread_pool.write.queue_size: 1000

# Index Settings
action.auto_create_index: .monitoring-*,.watches,.triggered_watches,.watcher-history-*

# Snapshot Settings
path.repo: ["/usr/share/elasticsearch/backups"]

# Logging
logger.level: INFO