pipelines:
  - pipeline.id: main
    path.config: "/usr/share/logstash/pipeline/logstash.conf"
    pipeline.workers: 2
    pipeline.batch.size: 125
    pipeline.batch.delay: 50
    queue.type: persisted
    queue.max_bytes: 1gb
    config.reload.automatic: true
    config.reload.interval: 3s
    dead_letter_queue.enable: true