.PHONY: install dev build clean

install:
	npm install

dev:
	npm run dev

build:
	npm run build

clean:
	rm -rf node_modules
	rm -rf dist

db-generate:
	npm run db:generate

db-push:
	npm run db:push

db-studio:
	npm run db:studio