# Order Service Makefile

.PHONY: install build start dev clean test lint

install:
	npm install

build:
	npm run build

start:
	npm start

dev:
	npm run dev

clean:
	rm -rf dist node_modules

test:
	npm test

lint:
	npm run lint

.DEFAULT_GOAL := dev